apiVersion: v1
kind: Service
metadata:
  name: hound
  labels:
    app: hound
    chart: hound-chart
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: hound
  ports:
  - name: hound
    protocol: TCP
    port: 6080
