package vcs

func init() {
	Register(newZip, "zip")
}

type ZipDriver struct{}

func newZip(b []byte) (Driver, error) {
	return &ZipDriver{}, nil
}

func (g *ZipDriver) HeadRev(dir string) (string, error) {
	return "n/a", nil
}

func (g *ZipDriver) Pull(dir string) (string, error) {
	return g.HeadRev(dir)
}

func (g *ZipDriver) Clone(dir, url string) (string, error) {
	return g.HeadRev(dir)
}

func (g *ZipDriver) SpecialFiles() []string {
	return []string{}
}

func (g *ZipDriver) AutoGeneratedFiles(dir string) []string {
	return []string{}
}
