on: [push]
jobs:
  go-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.13", "1.12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go }}
      - run: go build -x -work ./cmds/...
  node-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
  go-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.13", "1.12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go }}
      - run: go test -race ./...
  # There are no npm tests, yet.
